### ISSUE TITLE
make it work with a proxy

### ISSUE THREAD

**Issue by bru65pag** [mchwalisz/thingspeak#11]
I could not find a solution to make it work with a proxy (mandatory from most companies intranet). the python module Requests has such an option. Would that be possible to add as well when creating a channel object?

**Comment by mchwalisz** [comment]
You can use proxies by defining environment variables. On the other hand it would make sense to create a requests session per channel to reuse connections. Allowing to pass session object into the channel would allow also for using proxies.

http://docs.python-requests.org/en/master/user/advanced/#proxies
