### ISSUE TITLE
Import error: ImportError: No module named 'httplib'

### ISSUE THREAD

**Issue by McTschecker** [mchwalisz/thingspeak#13]
It looks like while importing it throws the error:
`>>> import thingspeak
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fabi/anaconda/lib/python3.5/site-packages/thingspeak.py", line 1, in <module>
    import httplib, urllib
ImportError: No module named 'httplib'`

**Comment by mchwalisz** [comment]
The file path doesn't seem correct. Could you give some more information about your setup?

`pip freeze` for example?

**Comment by McTschecker** [comment]
I am using a python 3 python environment with anaconda. I am on osx.

**Comment by mchwalisz** [comment]
`...site-packages/thingspeak.py` is very strange path. There shouldn't be anything like that if you installed `thingspeak` correctly. Do you maybe called something else `thingspeak.py` as well? it is probable that it is importing different module than you expect.

In the project I don't import `httplib` directly anyway.

You are not convincing me that it is problem with `thingspeak` package.
