### ISSUE TITLE
400 Client Error: Bad Request for url: https://api.thingspeak.com/

### ISSUE THREAD

**Issue by gitmopp** [mchwalisz/thingspeak#14]
Hello,

I tried the following sample code with python3 and I get the error:
`400 Client Error: Bad Request for url: https://api.thingspeak.com//channels/123456/feeds.json
`
If I open the URL using my browser and appending the `api_key=` I do not see any issues with the URL.
Code
```
import thingspeak
channel_id = 123456
write_key  = "XXXXXXXXXXXXXXXXX"

try:
  channel = thingspeak.Channel(id=channel_id,write_key=write_key)
  channel.get()
except Exception as e: print(e)
```

**Comment by gitmopp** [comment]
The function `get` expects to use api_key instead of write_key.
My code works like this:
` channel = thingspeak.Channel(id=channel_id,api_key=write_key)`
But it will not work if I use the value of my api_key. Maybe thingspeak changed the API in the past for security reasons.
From my understanding the api_key has to be replaced by the write_key or read_key in the file `thingspeak.py`

**Comment by mchwalisz** [comment]
it should work on develop branch
