### ISSUE TITLE
Support for other URL

### ISSUE THREAD

**Issue by ReiniervdL** [mchwalisz/thingspeak#6]
Hi Mikolaj,
Suggested feature: allow Thingspeak URL change, so I can run my own instance of thingspeak server.

**Comment by mchwalisz** [comment]
work in progress in dded0c55

**Comment by JavanXD** [comment]
@mchwalisz Would be nice if you could merge the custom thingspeak-server url into the master branch. Thanks!

At the moment _init_ is merged but not `thingspeak.py`.

**Comment by mchwalisz** [comment]
@JavanXD would you be able to test custom server using develop branch? I would be grateful for tests and `vcr cassettes` using custom server
